default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: face_letter_api_development

test:
  <<: *default
  database: face_letter_api_test

production:
  <<: *default
  database: face_letter_api_production
  username: <%= ENV["PRODUCTION_DATABASE_USER"] %>
  password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
